# Generated by Django 6.0.5 on 2026-05-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('analysed', 'Analysed'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=255),
        ),
    ]
