# Generated by Django 6.0.5 on 2026-05-18 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vacancy_id', models.CharField(max_length=255)),
                ('overall_score', models.IntegerField()),
                ('rating', models.CharField(max_length=50)),
                ('strengths', models.JSONField()),
                ('areas_to_improve', models.JSONField()),
                ('section_breakdown_percentage', models.JSONField()),
                ('keyword_analysis', models.JSONField()),
                ('projects', models.JSONField()),
                ('experience', models.JSONField()),
                ('final_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='applications.application')),
            ],
            options={
                'verbose_name_plural': 'analytics',
                'db_table': 'analytics',
            },
        ),
    ]
